name: flutter_linkify_example
description: flutter_linkify example

version: 1.0.0+1

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter_web: any
  flutter_linkify:
    path: ..

dev_dependencies:
  build_runner: ^1.5.0
  build_daemon: ^1.0.0
  build_web_compilers: ^2.0.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
