name: flutter_linkify
description: Turns text URLs and emails into clickable inline links in text for Flutter.
version: 2.1.0
author: Charles Crete <charles@cretezy.com>
homepage: https://github.com/Cretezy/flutter_linkify

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter_web: any
  linkify: ^1.0.0

dev_dependencies:
  pedantic: ^1.4.0


# flutter_web packages are not published to pub.dartlang.org
# These overrides tell the package tools to get them from GitHub
dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
